PhoenixUserAuth/web/router.ex
defmodule UserAuth.Router do
  use UserAuth.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", UserAuth do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/earlybird", PageController, :show
    resources "/registrations", RegistrationController, only: [:new, :create]
    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
    # get "/earlybird", EarlyBirdController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", UserAuth do
    pipe_through :api

    get "/users", UserController, :index
    get "/users/:id", UserController, :show
    post "/users", UserController, :create
    put "/users/:id", UserController, :update
  end
end

PhoenixUserAuth/web/views/layout_view.ex
defmodule UserAuth.LayoutView do
  use UserAuth.Web, :view
end

PhoenixUserAuth/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Early Bird">
    <meta name="author" content="Mina Melosh">

    <title>Early Bird User Auth</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if logged_in?(@conn) do %>

              <li><%= link "Logout", to: session_path(@conn, :delete), method: :delete %></li>
            <%= else %>
              <li><%= link "Register", to: registration_path(@conn, :new) %></li>
              <li><%= link "Login", to: session_path(@conn, :new) %></li>
            <%= end %>
            <li><%= link "Home", to: page_path(@conn, :index) %></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>